server:
  port: 0

spring:
  application:
    name: petcast-member-service

  ## db config
  datasource:

#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:8080/pet_cast
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/pet_cast
    username: swcamp
    password: swcamp

  ## jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
  config:
    import:
      - classpath:/bootstrap.yml

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


token:
  expiration_time: 43200000
  secret: CdkKVDgED/8zH71UEu1kRNaeI9/rWJiGxiT+ht0u5QaVjOXKkx//t+hLqtTgwqEGWDuQaz07ze60vVX8LTnlKQ==