server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    server-url:
      defaultZone: http://localhost:8761/service-discovery

spring:
  application:
    name: gateway
  config:
    import:
      - classpath:/bootstrap.yml

  cloud:
    gateway:
      routes:
        - id: service-member-signup
          uri: lb://PETCAST-MEMBER-SERVICE
          predicates:
            - Path=/service-member/api/v1/members/sign-up
            - Method=POST
          filters:
            - RewritePath=/service-member/(?<segment>.*), /$\{segment}

        - id: service-member-login
          uri: lb://PETCAST-MEMBER-SERVICE
          predicates:
            - Path=/service-member/login
            - Method=POST
          filters:
            - RewritePath=/service-member/(?<segment>.*), /$\{segment}

        - id: service-member
          uri: lb://PETCAST-MEMBER-SERVICE
          predicates:
            - Path=/service-member/**
            - Method=GET
          filters:
            - RewritePath=/service-member/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: service-member-other-post
          uri: lb://PETCAST-MEMBER-SERVICE
          predicates:
            - Path=/service-member/**
            - Method=POST
          filters:
            - RewritePath=/service-member/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: service-member-put
          uri: lb://PETCAST-MEMBER-SERVICE
          predicates:
            - Path=/service-member/**
            - Method=PUT
          filters:
            - RewritePath=/service-member/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: service-others
          uri: lb://PETCAST-OTHERS-SERVICE
          predicates:
            - Path=/service-others/**
          filters:
            - RewritePath=/service-others/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

token:
  secret: CdkKVDgED/8zH71UEu1kRNaeI9/rWJiGxiT+ht0u5QaVjOXKkx//t+hLqtTgwqEGWDuQaz07ze60vVX8LTnlKQ==